services:
  auth_server:
    container_name: auth_server
    build: .
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000
    depends_on:
      - auth_db

  auth_db:
    container_name: auth_db
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth
    volumes:
      - auth_db_data:/var/lib/postgresql/data

  adminer:
    container_name: adminer
    image: adminer
    ports:
      - 5000:8080
    depends_on:
      - auth_db

volumes:
  auth_db_data: